<?php

/*
* Implementing Hook Menu
*/

function menu_menu(){
  $items['test_menu'] = array(
  'title' => 'Hook Menu Example',
  'access arguments' => 'access content',
  'page callback' => 'menu_callback'
  );
  return $items;
}

/*----- Callback function from the menu -----*/
function menu_callback(){
  $output = array(
    '#theme' => 'menu_template',
    /*-- variables --*/
    '#first_text' => $first_text,
    '#second_text' => $second_text,
  );
  return $output;
}

/*  ---- Hook Theme --
* Defines a returned array with the template => an array
*
---*/
function menu_theme($existing, $type, $theme, $path){
  return array(
      'menu_template' => array(
          'template' => 'menu_template',
          'variables' => array(
             'first_text' => 'Show time',
             'second_text' => NULL,
         ),
      ),
  );
}
