<?php

/*
* Implementing hook_block_info
*/

function blockForm_block_info(){
   $blocks['form block'] = array(
   'info' => 'Block Form',
   );
 return $blocks;
}

/*
* Implementing hook_block_view
*/
function blockForm_block_view($delta = ''){
   $blocks = array();
     switch($delta){
     case 'form block' :
     $blocks['subject'] = t('Form block');
     $blocks['content'] = drupal_get_form('blockForm_form');
   };
 return $blocks;
}

/*
* Implementing hook_form
*/

function blockForm_form($node, &$form_state){

    $form['name'] = array(
    '#type' => 'textfield',
    '#required' => 'True',
    '#title' => t('Name'),
    '#maxlength' => 127,
  );

     $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
    '#maxlength' => 127,
  );

     $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#maxlength' => 127,
  );

     $form['submit'] = array(
    '#type' => 'submit',
    '#title' => t('submit'),
    '#value' => 'submit',
  );
    return $form;
}

/*
* Implementing hook_form_submit
*/

function blockForm_form_submit($node, &$form_state){

    if($form_state['values']['name'] != " "){
        drupal_set_message('Hello' .' '.$form_state['values']['name']);
    }
    else{
        drupal_set_message('Please enter your username');
    }

}

/*
* Implementing hook_theme()


function blockForm_theme($existing, $type, $theme, $path){
    return array(
        'blockForm_item' => array(
            'template' => 'blockForm_item',
            'variables' => array(
               'title' => NULL,
               'items' => NULL,
           ),
        ),
    );

}


/*
* Implementing theme_hook



function theme_blockForm($variables) {
    extract($variables);
    drupal_add_css(drupal_get_path('module', 'blockForm.css') );
    return '' . $element['#children'] . '';
}
*/
